Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
  	node1.vm.box = "centos/7"
  	node1.vm.hostname = "CentOS"
  	node1.vm.network "private_network", ip: "10.10.10.11"
    node1.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	  node1.vm.provision "shell",
            inline: "/bin/sh /vagrant/bootstrap.sh"
  #         inline: "sudo yum install epel-release -y"
  end

  #config.vm.define "node2" do |node2|
  #  node2.vm.box = "ubuntu/bionic64"
  #  node2.vm.hostname = "Ubuntu"
  #  node2.vm.network "private_network", ip: "10.10.10.12"
  #end
end
